"""empty message

Revision ID: 59b4384f44b7
Revises: 
Create Date: 2022-03-26 10:54:30.906904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b4384f44b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_brand', sa.String(length=100), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('car_license_plate', sa.String(length=20), nullable=True),
    sa.Column('car_type', sa.String(length=100), nullable=True),
    sa.Column('release_year', sa.DateTime(), nullable=True),
    sa.Column('trailer', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_license_plate')
    )
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('cars')
    # ### end Alembic commands ###
